export const tarotDeck = [
  {
    name: "Ace of Cups",
    upright: "Love, new relationships, compassion, creativity",
    reversed: "Self-love, repressed emotions",
    imageUrl: "tarot_images/Ace of Cups.png",
  },
  {
    name: "Ace of Pentacles",
    upright: "A new financial or career opportunity, manifestation, abundance",
    reversed: "Lost opportunity, lack of planning and foresight",
    imageUrl: "tarot_images/Ace of Pentacles.png",
  },
  {
    name: "Ace of Swords",
    upright: "Breakthrough, clarity, sharp mind",
    reversed: "Clouded judgment, poor decisions",
    imageUrl: "tarot_images/Ace of Swords.png",
  },
  {
    name: "Ace of Wands",
    upright: "Inspiration, new opportunities, growth, potential",
    reversed: "An emerging idea, lack of direction, distractions, delays",
    imageUrl: "tarot_images/Ace of Wands.png",
  },
  {
    name: "Death",
    upright: "Endings, change, transformation, transition",
    reversed: "Resistance to change, personal transformation, inner purging",
    imageUrl: "tarot_images/Death.png",
  },
  {
    name: "Eight of Cups",
    upright: "Disappointment, abandonment, withdrawal, escapism",
    reversed: "Trying one more time, indecision, aimless drifting",
    imageUrl: "tarot_images/Eight of Cups.png",
  },
  {
    name: "Eight of Pentacles",
    upright: "Apprenticeship, repetitive tasks, mastery, skill development",
    reversed: "Self-development, perfectionism, misdirected activity",
    imageUrl: "tarot_images/Eight of Pentacles.png",
  },
  {
    name: "Eight of Swords",
    upright: "Isolation, self-imposed restriction, imprisonment",
    reversed: "Open to new perspectives",
    imageUrl: "tarot_images/Eight of Swords.png",
  },
  {
    name: "Eight of Wands",
    upright: "Movement, fast-paced change, action, alignment",
    reversed: "Delays, frustration, holding off",
    imageUrl: "tarot_images/Eight of Wands.png",
  },
  {
    name: "Five of Cups",
    upright: "Regret, failure, disappointment, pessimism",
    reversed: "Personal setbacks, self-forgiveness, moving on",
    imageUrl: "tarot_images/Five of Cups.png",
  },
  {
    name: "Five of Pentacles",
    upright: "Financial loss, poverty, lack mindset, isolation, worry",
    reversed: "Recovery from financial loss, spiritual poverty",
    imageUrl: "tarot_images/Five of Pentacles.png",
  },
  {
    name: "Five of Swords",
    upright: "Conflict, disagreements, defeat, betrayal",
    reversed: "Reconciliation, making amends",
    imageUrl: "tarot_images/Five of Swords.png",
  },
  {
    name: "Five of Wands",
    upright: "Conflict, disagreements, competition, tension, diversity",
    reversed: "Inner conflict, conflict avoidance, tension release",
    imageUrl: "tarot_images/Five of Wands.png",
  },
  {
    name: "Four of Cups",
    upright: "Meditation, contemplation, apathy, re-evaluation",
    reversed: "Retreat, withdrawal, checking in for alignment",
    imageUrl: "tarot_images/Four of Cups.png",
  },
  {
    name: "Four of Pentacles",
    upright: "Saving money, security, conservatism, scarcity, control",
    reversed: "Over-spending, greed, self-protection",
    imageUrl: "tarot_images/Four of Pentacles.png",
  },
  {
    name: "Four of Swords",
    upright: "Rest, relaxation, meditation, contemplation",
    reversed: "Exhaustion, burnout, deep contemplation",
    imageUrl: "tarot_images/Four of Swords.png",
  },
  {
    name: "Four of Wands",
    upright: "Celebration, joy, harmony, relaxation, homecoming",
    reversed: "Personal celebration, inner harmony, conflict with others",
    imageUrl: "tarot_images/Four of Wands.png",
  },
  {
    name: "Judgement",
    upright: "Judgement, rebirth, inner calling, absolution",
    reversed: "Self-doubt, inner critic, ignoring the call",
    imageUrl: "tarot_images/Judgement.png",
  },
  {
    name: "Justice",
    upright: "Justice, fairness, truth, cause and effect, law",
    reversed: "Unfairness, lack of accountability, dishonesty",
    imageUrl: "tarot_images/Justice.png",
  },
  {
    name: "King of Cups",
    upright: "Emotionally balanced, compassionate, diplomatic",
    reversed: "Emotional manipulation, moodiness, volatility",
    imageUrl: "tarot_images/King of Cups.png",
  },
  {
    name: "King of Pentacles",
    upright: "Wealth, business, leadership, security, discipline, abundance",
    reversed: "Financially inept, obsessed with wealth and status, stubborn",
    imageUrl: "tarot_images/King of Pentacles.png",
  },
  {
    name: "King of Swords",
    upright: "Mental clarity, intellectual power, authority, truth",
    reversed: "Manipulative, tyrannical, abusive",
    imageUrl: "tarot_images/King of Swords.png",
  },
  {
    name: "King of Wands",
    upright: "Natural leader, vision, entrepreneur, honor",
    reversed: "Impulsiveness, haste, ruthless, high expectations",
    imageUrl: "tarot_images/King of Wands.png",
  },
  {
    name: "Knight of Cups",
    upright: "Romance, charm, beauty, imagination",
    reversed: "Moodiness, unrealistic expectations",
    imageUrl: "tarot_images/Knight of Cups.png",
  },
  {
    name: "Knight of Pentacles",
    upright: "Hard work, productivity, routine, conservatism",
    reversed: "Self-discipline, boredom, feeling 'stuck', perfectionism",
    imageUrl: "tarot_images/Knight of Pentacles.png",
  },
  {
    name: "Knight of Swords",
    upright: "Ambitious, action-oriented, driven to succeed, fast-thinking",
    reversed: "Restless, unfocused, impulsive, burn-out",
    imageUrl: "tarot_images/Knight of Swords.png",
  },
  {
    name: "Knight of Wands",
    upright: "Action, adventure, fearlessness",
    reversed: "Anger, recklessness, frustration",
    imageUrl: "tarot_images/Knight of Wands.png",
  },
  {
    name: "Nine of Cups",
    upright: "Contentment, satisfaction, gratitude, wish come true",
    reversed: "Inner happiness, materialism, dissatisfaction",
    imageUrl: "tarot_images/Nine of Cups.png",
  },
  {
    name: "Nine of Pentacles",
    upright: "Abundance, luxury, self-sufficiency, financial independence",
    reversed: "Self-worth, over-investment in work, hustling",
    imageUrl: "tarot_images/Nine of Pentacles.png",
  },
  {
    name: "Nine of Swords",
    upright: "Anxiety, worry, fear, depression, nightmares",
    reversed: "Inner turmoil, deep-seated fears",
    imageUrl: "tarot_images/Nine of Swords.png",
  },
  {
    name: "Nine of Wands",
    upright: "Resilience, courage, persistence, test of faith, boundaries",
    reversed: "Inner resources, struggle, overwhelm, defensive",
    imageUrl: "tarot_images/Nine of Wands.png",
  },
  {
    name: "Page of Cups",
    upright:
      "Creative opportunities, intuitive messages, curiosity, possibility",
    reversed: "Emotional immaturity, insecurity, disappointment",
    imageUrl: "tarot_images/Page of Cups.png",
  },
  {
    name: "Page of Pentacles",
    upright: "Manifestation, financial opportunity, skill development",
    reversed: "Lack of progress, procrastination, learn from failure",
    imageUrl: "tarot_images/Page of Pentacles.png",
  },
  {
    name: "Page of Swords",
    upright:
      "New ideas, curiosity, thirst for knowledge, new ways of communicating",
    reversed:
      "Self-expression, all talk and no action, haphazard action, haste",
    imageUrl: "tarot_images/Page of Swords.png",
  },
  {
    name: "Page of Wands",
    upright: "Exploration, excitement, freedom, discovery",
    reversed: "Lack of direction, procrastination, setbacks",
    imageUrl: "tarot_images/Page of Wands.png",
  },
  {
    name: "Queen of Cups",
    upright: "Compassionate, caring, emotionally stable, intuitive",
    reversed: "Emotional insecurity, co-dependency",
    imageUrl: "tarot_images/Queen of Cups.png",
  },
  {
    name: "Queen of Pentacles",
    upright: "Nurturing, practical, providing financially, a working parent",
    reversed: "Financial independence, self-care, work-home conflict",
    imageUrl: "tarot_images/Queen of Pentacles.png",
  },
  {
    name: "Queen of Swords",
    upright:
      "Independent, unbiased judgment, clear boundaries, direct communication",
    reversed: "Overly emotional, easily influenced, cold-hearted",
    imageUrl: "tarot_images/Queen of Swords.png",
  },
  {
    name: "Queen of Wands",
    upright: "Courage, confidence, independence, social butterfly",
    reversed: "Selfishness, jealousy, insecurity",
    imageUrl: "tarot_images/Queen of Wands.png",
  },
  {
    name: "Seven of Cups",
    upright: "Opportunities, choices, wishful thinking, illusion",
    reversed: "Alignment, personal values, overwhelmed by choices",
    imageUrl: "tarot_images/Seven of Cups.png",
  },
  {
    name: "Seven of Pentacles",
    upright: "Long-term view, sustainable results, perseverance, investment",
    reversed: "Lack of long-term vision, limited success or reward",
    imageUrl: "tarot_images/Seven of Pentacles.png",
  },
  {
    name: "Seven of Swords",
    upright: "Deception, trickery, tactics and strategy",
    reversed: "Impulsiveness, coming clean",
    imageUrl: "tarot_images/Seven of Swords.png",
  },
  {
    name: "Seven of Wands",
    upright: "Challenge, competition, protection, perseverance",
    reversed: "Exhaustion, giving up, overwhelmed",
    imageUrl: "tarot_images/Seven of Wands.png",
  },
  {
    name: "Six of Cups",
    upright: "Revisiting childhood memories, innocence, joy",
    reversed: "Stuck in the past, naivety, unrealistic",
    imageUrl: "tarot_images/Six of Cups.png",
  },
  {
    name: "Six of Pentacles",
    upright: "Giving, receiving, sharing wealth, generosity, charity",
    reversed: "Self-care, unpaid debts, one-sided charity",
    imageUrl: "tarot_images/Six of Pentacles.png",
  },
  {
    name: "Six of Swords",
    upright: "Transition, change, rite of passage",
    reversed: "Resisting change, unfinished business",
    imageUrl: "tarot_images/Six of Swords.png",
  },
  {
    name: "Six of Wands",
    upright: "Success, public recognition, progress, self-confidence",
    reversed:
      "Private achievement, personal definition of success, fall from grace",
    imageUrl: "tarot_images/Six of Wands.png",
  },
  {
    name: "Strength",
    upright: "Strength, courage, persuasion, influence, compassion",
    reversed: "Inner strength, self-doubt, low energy, raw emotion",
    imageUrl: "tarot_images/Strength.png",
  },
  {
    name: "Temperance",
    upright: "Balance, moderation, patience, purpose",
    reversed: "Imbalance, excess, self-healing, re-alignment",
    imageUrl: "tarot_images/Temperance.png",
  },
  {
    name: "Ten of Cups",
    upright: "Divine love, blissful relationships, harmony, alignment",
    reversed: "Disconnection, misaligned values, struggling relationships",
    imageUrl: "tarot_images/Ten of Cups.png",
  },
  {
    name: "Ten of Pentacles",
    upright:
      "Wealth, financial security, family, long-term success, contribution",
    reversed: "The dark side of wealth, financial failure or loss",
    imageUrl: "tarot_images/Ten of Pentacles.png",
  },
  {
    name: "Ten of Swords",
    upright: "Painful endings, betrayal, loss, crisis",
    reversed: "Regeneration, recovery",
    imageUrl: "tarot_images/Ten of Swords.png",
  },
  {
    name: "Ten of Wands",
    upright: "Burden, extra responsibility, hard work, completion",
    reversed: "Doing it all, carrying the burden, delegation",
    imageUrl: "tarot_images/Ten of Wands.png",
  },
  {
    name: "The Chariot",
    upright: "Control, willpower, success, action, determination",
    reversed: "Self-discipline, opposition, lack of direction",
    imageUrl: "tarot_images/The Chariot.png",
  },
  {
    name: "The Devil",
    upright: "Shadow self, attachment, addiction, restriction, sexuality",
    reversed: "Releasing limiting beliefs, exploring dark thoughts, detachment",
    imageUrl: "tarot_images/The Devil.png",
  },
  {
    name: "The Emperor",
    upright: "Authority, establishment, structure, a father figure",
    reversed:
      "Domination, excessive control, lack of discipline, inflexibility",
    imageUrl: "tarot_images/The Emperor.png",
  },
  {
    name: "The Empress",
    upright: "Femininity, beauty, nature, nurturing, abundance",
    reversed: "Creative block, dependence on others",
    imageUrl: "tarot_images/The Empress.png",
  },
  {
    name: "The Hanged Man",
    upright: "Pause, surrender, letting go, new perspectives",
    reversed: "Delays, resistance, stalling, indecision",
    imageUrl: "tarot_images/The Hanged Man.png",
  },
  {
    name: "The Hermit",
    upright: "Soul-searching, introspection, being alone, inner guidance",
    reversed: "Isolation, loneliness, withdrawal",
    imageUrl: "tarot_images/The Hermit.png",
  },
  {
    name: "The Hierophant",
    upright: "Spiritual wisdom, religious beliefs, conformity, tradition",
    reversed: "Personal beliefs, freedom, challenging the status quo",
    imageUrl: "tarot_images/The Hierophant.png",
  },
  {
    name: "The High Priestess",
    upright: "Intuition, sacred knowledge, divine feminine, subconscious mind",
    reversed: "Secrets, disconnected from intuition, withdrawal, silence",
    imageUrl: "tarot_images/The High Priestess.png",
  },
  {
    name: "The Lovers",
    upright: "Love, harmony, relationships, values alignment, choices",
    reversed: "Self-love, disharmony, imbalance, misalignment of values",
    imageUrl: "tarot_images/The Lovers.png",
  },
  {
    name: "The Moon",
    upright: "Illusion, fear, anxiety, subconscious, intuition",
    reversed: "Release of fear, repressed emotion, inner confusion",
    imageUrl: "tarot_images/The Moon.png",
  },
  {
    name: "The Star",
    upright: "Hope, faith, purpose, renewal, spirituality",
    reversed: "Lack of faith, despair, self-trust, disconnection",
    imageUrl: "tarot_images/The Star.png",
  },
  {
    name: "The Sun",
    upright: "Positivity, fun, warmth, success, vitality",
    reversed: "Inner child, feeling down, overly optimistic",
    imageUrl: "tarot_images/The Sun.png",
  },
  {
    name: "The Tower",
    upright: "Sudden change, upheaval, chaos, revelation, awakening",
    reversed: "Personal transformation, fear of change, averting disaster",
    imageUrl: "tarot_images/The Tower.png",
  },
  {
    name: "The World",
    upright: "Completion, integration, accomplishment, travel",
    reversed: "Seeking personal closure, short-cuts, delays",
    imageUrl: "tarot_images/The World.png",
  },
  {
    name: "Three of Cups",
    upright: "Celebration, friendship, creativity, collaborations",
    reversed:
      "Independence, alone time, hardcore partying, 'three\u2019s a crowd'",
    imageUrl: "tarot_images/Three of Cups.png",
  },
  {
    name: "Three of Pentacles",
    upright: "Teamwork, collaboration, learning, implementation",
    reversed: "Disharmony, misalignment, working alone",
    imageUrl: "tarot_images/Three of Pentacles.png",
  },
  {
    name: "Three of Swords",
    upright: "Heartbreak, emotional pain, sorrow, grief, hurt",
    reversed: "Negative self-talk, releasing pain, optimism",
    imageUrl: "tarot_images/Three of Swords.png",
  },
  {
    name: "Three of Wands",
    upright: "Progress, expansion, foresight, overseas opportunities",
    reversed: "Playing small, lack of foresight, unexpected delays",
    imageUrl: "tarot_images/Three of Wands.png",
  },
  {
    name: "Two of Cups",
    upright: "Unified love, partnership, mutual attraction",
    reversed: "Self-love, break-ups, disharmony, distrust",
    imageUrl: "tarot_images/Two of Cups.png",
  },
  {
    name: "Two of Pentacles",
    upright:
      "Multiple priorities, time management, prioritization, adaptability",
    reversed: "Over-committed, disorganization, reprioritization",
    imageUrl: "tarot_images/Two of Pentacles.png",
  },
  {
    name: "Two of Swords",
    upright: "Difficult decisions, weighing up options, an impasse",
    reversed: "Indecision, confusion, information overload",
    imageUrl: "tarot_images/Two of Swords.png",
  },
  {
    name: "Two of Wands",
    upright: "Future planning, progress, decisions, discovery",
    reversed:
      "Personal goals, inner alignment, fear of unknown, lack of planning",
    imageUrl: "tarot_images/Two of Wands.png",
  },
  {
    name: "Wheel of Fortune",
    upright: "Good luck, karma, life cycles, destiny, a turning point",
    reversed: "Bad luck, resistance to change, breaking cycles",
    imageUrl: "tarot_images/Wheel of Fortune.png",
  },
  {
    name: "The Fool",
    upright: "New beginnings, adventure, innocence, freedom",
    reversed: "Recklessness, na\u00efvet\u00e9, fear, holding back",
    imageUrl: "tarot_images/the fool.png",
  },
  {
    name: "The Magician",
    upright: "Manifestation, resourcefulness, power, inspired action",
    reversed: "Manipulation, poor planning, latent talents",
    imageUrl: "tarot_images/the magician.png",
  },
];
